// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const centered: string;
export const padTop: string;
export const padBottom: string;
export const padLeft: string;
export const padRight: string;
