// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const p: string;
export const l: string;
export const fe: string;
export const eng: string;
export const blog: string;
export const topRow: string;
export const md: string;
