// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const header: string;
export const title: string;
export const date: string;
export const image: string;
export const centerer: string;
export const readMore: string;
export const icon: string;
export const footer: string;
