// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const list: string;
export const item: string;
export const link: string;
export const previous: string;
export const next: string;
export const imageWrapper: string;
export const right: string;
